<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run()
    {
        $products = [

            // ─────────────────────────────────────────
            // LAPTOPS
            // ─────────────────────────────────────────
            [
                'name'           => 'MacBook Pro 16" M3 Chip',
                'description'    => 'The most powerful MacBook Pro ever with the M3 Pro chip, 18GB unified memory, and 512GB SSD storage. Perfect for professionals.',
                'price'          => 2499.99,
                'original_price' => 2799.99,
                'image'          => 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&h=600&fit=crop',
                'rating'         => 4.9,
                'reviews'        => 3245,
                'category'       => 'Laptops',
                'brand'          => 'Apple',
                'stock'          => 15,
                'is_new'         => true,
                'is_featured'    => true,
                'discount'       => 11,
                'specifications' => json_encode([
                    'processor' => 'Apple M3 Pro (12-core)',
                    'ram'       => '18GB Unified',
                    'storage'   => '512GB SSD',
                    'display'   => '16.2-inch Liquid Retina XDR',
                    'battery'   => 'Up to 22 hours',
                    'weight'    => '4.7 lbs',
                ]),
                'features' => json_encode([
                    'M3 Pro Chip',
                    'Liquid Retina XDR Display',
                    '1080p FaceTime HD Camera',
                    'Six-speaker sound system',
                    'Studio-quality mics',
                ]),
            ],
            [
                'name'           => 'Dell XPS 15',
                'description'    => 'Premium laptop with InfinityEdge display, Intel Core i7, 16GB RAM, 512GB SSD.',
                'price'          => 1899.99,
                'original_price' => 2099.99,
                'image'          => 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=600&h=600&fit=crop',
                'rating'         => 4.7,
                'reviews'        => 1892,
                'category'       => 'Laptops',
                'brand'          => 'Dell',
                'stock'          => 8,
                'is_new'         => false,
                'is_featured'    => true,
                'discount'       => 10,
                'specifications' => json_encode([
                    'processor' => 'Intel Core i7-13700H',
                    'ram'       => '16GB DDR5',
                    'storage'   => '512GB SSD',
                    'display'   => '15.6-inch 3.5K OLED',
                    'battery'   => 'Up to 15 hours',
                ]),
                'features' => json_encode([
                    'InfinityEdge Display',
                    'Dolby Vision',
                    'Fingerprint Reader',
                    'Backlit Keyboard',
                ]),
            ],
            [
                'name'           => 'ASUS ROG Zephyrus G14',
                'description'    => 'Ultra-slim gaming laptop with AMD Ryzen 9, NVIDIA RTX 4060, and a stunning 165Hz display.',
                'price'          => 1549.99,
                'original_price' => 1749.99,
                'image'          => 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=600&h=600&fit=crop',
                'rating'         => 4.7,
                'reviews'        => 2134,
                'category'       => 'Laptops',
                'brand'          => 'ASUS',
                'stock'          => 20,
                'is_new'         => true,
                'is_featured'    => true,
                'discount'       => 11,
                'specifications' => json_encode([
                    'processor' => 'AMD Ryzen 9 7940HS',
                    'gpu'       => 'NVIDIA GeForce RTX 4060',
                    'ram'       => '16GB DDR5',
                    'storage'   => '1TB NVMe SSD',
                    'display'   => '14-inch 2.5K 165Hz',
                    'battery'   => 'Up to 10 hours',
                ]),
                'features' => json_encode([
                    'ROG Nebula Display',
                    'MUX Switch',
                    'AniMe Matrix LED Cover',
                    'Dolby Atmos Audio',
                    'Wi-Fi 6E',
                ]),
            ],
            [
                'name'           => 'Lenovo ThinkPad X1 Carbon Gen 11',
                'description'    => 'Legendary business laptop — featherlight at 2.48 lbs, Intel vPro, and enterprise-grade security.',
                'price'          => 1649.99,
                'original_price' => 1899.99,
                'image'          => 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600&h=600&fit=crop',
                'rating'         => 4.8,
                'reviews'        => 1543,
                'category'       => 'Laptops',
                'brand'          => 'Lenovo',
                'stock'          => 10,
                'is_new'         => false,
                'is_featured'    => false,
                'discount'       => 13,
                'specifications' => json_encode([
                    'processor' => 'Intel Core i7-1365U vPro',
                    'ram'       => '16GB LPDDR5',
                    'storage'   => '512GB SSD',
                    'display'   => '14-inch 2.8K OLED',
                    'battery'   => 'Up to 15 hours',
                    'weight'    => '2.48 lbs',
                ]),
                'features' => json_encode([
                    'MIL-SPEC Durability',
                    'Fingerprint + IR Camera',
                    'ThinkShield Security',
                    'Rapid Charge (80% in 1hr)',
                    'Thunderbolt 4',
                ]),
            ],

            // ─────────────────────────────────────────
            // SMARTPHONES
            // ─────────────────────────────────────────
            [
                'name'           => 'iPhone 15 Pro Max',
                'description'    => 'Titanium design, A17 Pro chip, 48MP camera system, and USB-C with USB 3 speeds.',
                'price'          => 1199.99,
                'original_price' => 1299.99,
                'image'          => 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=600&h=600&fit=crop',
                'rating'         => 4.9,
                'reviews'        => 11234,
                'category'       => 'Smartphones',
                'brand'          => 'Apple',
                'stock'          => 30,
                'is_new'         => true,
                'is_featured'    => true,
                'discount'       => 8,
                'specifications' => json_encode([
                    'processor'  => 'A17 Pro (3nm)',
                    'ram'        => '8GB',
                    'storage'    => '256GB',
                    'display'    => '6.7-inch Super Retina XDR ProMotion',
                    'camera'     => '48MP Main + 12MP Ultra Wide + 12MP Telephoto',
                    'battery'    => '4422 mAh',
                ]),
                'features' => json_encode([
                    'Action Button',
                    'ProRes Video Recording',
                    'USB 3 Transfer Speeds',
                    'Emergency SOS via Satellite',
                    'Always-On Display',
                ]),
            ],
            [
                'name'           => 'Samsung Galaxy S24 Ultra',
                'description'    => 'Galaxy AI, built-in S Pen, 200MP camera, and 100× Space Zoom for the ultimate Android flagship.',
                'price'          => 1299.99,
                'original_price' => 1399.99,
                'image'          => 'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=600&h=600&fit=crop',
                'rating'         => 4.8,
                'reviews'        => 8765,
                'category'       => 'Smartphones',
                'brand'          => 'Samsung',
                'stock'          => 22,
                'is_new'         => true,
                'is_featured'    => true,
                'discount'       => 7,
                'specifications' => json_encode([
                    'processor' => 'Snapdragon 8 Gen 3',
                    'ram'       => '12GB',
                    'storage'   => '256GB',
                    'display'   => '6.8-inch Dynamic AMOLED 2X 120Hz',
                    'camera'    => '200MP Main + 12MP Ultra Wide + 50MP Periscope',
                    'battery'   => '5000 mAh',
                ]),
                'features' => json_encode([
                    'Built-in S Pen',
                    'Galaxy AI Features',
                    '100× Space Zoom',
                    'Titanium Frame',
                    'IP68 Water Resistance',
                ]),
            ],
            [
                'name'           => 'Google Pixel 8 Pro',
                'description'    => 'Google Tensor G3 chip with AI-powered photography, 7 years of OS updates, and temperature sensor.',
                'price'          => 899.99,
                'original_price' => 999.99,
                'image'          => 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=600&h=600&fit=crop',
                'rating'         => 4.7,
                'reviews'        => 5432,
                'category'       => 'Smartphones',
                'brand'          => 'Google',
                'stock'          => 18,
                'is_new'         => true,
                'is_featured'    => false,
                'discount'       => 10,
                'specifications' => json_encode([
                    'processor' => 'Google Tensor G3',
                    'ram'       => '12GB',
                    'storage'   => '128GB',
                    'display'   => '6.7-inch LTPO OLED 120Hz',
                    'camera'    => '50MP Main + 48MP Ultra Wide + 48MP Telephoto',
                    'battery'   => '5050 mAh',
                ]),
                'features' => json_encode([
                    'Magic Eraser',
                    'Best Take & Photo Unblur',
                    'Temperature Sensor',
                    '7 Years OS Updates',
                    'Satellite Emergency SOS',
                ]),
            ],

            // ─────────────────────────────────────────
            // TABLETS
            // ─────────────────────────────────────────
            [
                'name'           => 'iPad Pro 12.9" M2',
                'description'    => 'Supercomputer-class M2 chip, Liquid Retina XDR display, and Thunderbolt / USB 4 connectivity.',
                'price'          => 1099.99,
                'original_price' => 1199.99,
                'image'          => 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600&h=600&fit=crop',
                'rating'         => 4.9,
                'reviews'        => 4321,
                'category'       => 'Tablets',
                'brand'          => 'Apple',
                'stock'          => 14,
                'is_new'         => false,
                'is_featured'    => true,
                'discount'       => 8,
                'specifications' => json_encode([
                    'processor'  => 'Apple M2',
                    'ram'        => '8GB',
                    'storage'    => '256GB',
                    'display'    => '12.9-inch Liquid Retina XDR',
                    'battery'    => 'Up to 10 hours',
                    'connector'  => 'Thunderbolt / USB 4',
                ]),
                'features' => json_encode([
                    'ProMotion 120Hz',
                    'Apple Pencil 2 Support',
                    'Magic Keyboard Compatible',
                    'Center Stage Camera',
                    'Wi-Fi 6E',
                ]),
            ],
            [
                'name'           => 'Samsung Galaxy Tab S9 Ultra',
                'description'    => '14.6-inch Dynamic AMOLED 2X display, Snapdragon 8 Gen 2, and included S Pen for creative work.',
                'price'          => 1099.99,
                'original_price' => 1199.99,
                'image'          => 'https://images.unsplash.com/photo-1561154464-82e9adf32764?w=600&h=600&fit=crop',
                'rating'         => 4.7,
                'reviews'        => 2876,
                'category'       => 'Tablets',
                'brand'          => 'Samsung',
                'stock'          => 11,
                'is_new'         => true,
                'is_featured'    => false,
                'discount'       => 8,
                'specifications' => json_encode([
                    'processor' => 'Snapdragon 8 Gen 2',
                    'ram'       => '12GB',
                    'storage'   => '256GB',
                    'display'   => '14.6-inch Dynamic AMOLED 2X 120Hz',
                    'battery'   => '11200 mAh',
                ]),
                'features' => json_encode([
                    'S Pen Included',
                    'DeX Desktop Mode',
                    'IP68 Water Resistance',
                    'Dolby Atmos Quad Speakers',
                    'Wi-Fi 6E',
                ]),
            ],

            // ─────────────────────────────────────────
            // AUDIO
            // ─────────────────────────────────────────
            [
                'name'           => 'Sony WH-1000XM5',
                'description'    => 'Industry-leading noise cancellation with exceptional sound quality and all-day comfort.',
                'price'          => 349.99,
                'original_price' => 399.99,
                'image'          => 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=600&h=600&fit=crop',
                'rating'         => 4.8,
                'reviews'        => 5678,
                'category'       => 'Audio',
                'brand'          => 'Sony',
                'stock'          => 42,
                'is_new'         => true,
                'is_featured'    => true,
                'discount'       => 12,
                'specifications' => json_encode([
                    'type'             => 'Over-ear',
                    'connectivity'     => 'Bluetooth 5.2',
                    'battery'          => '30 hours',
                    'noise_cancelling' => 'Yes',
                    'weight'           => '250g',
                ]),
                'features' => json_encode([
                    'Industry-leading NC',
                    '30-hour battery',
                    'Quick charging',
                    'Multipoint connection',
                    'Speak-to-chat',
                ]),
            ],
            [
                'name'           => 'Apple AirPods Pro 2',
                'description'    => 'Active Noise Cancellation, Transparency mode, Spatial Audio, and improved battery life.',
                'price'          => 199.99,
                'original_price' => 249.99,
                'image'          => 'https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=600&h=600&fit=crop',
                'rating'         => 4.9,
                'reviews'        => 8921,
                'category'       => 'Audio',
                'brand'          => 'Apple',
                'stock'          => 35,
                'is_new'         => true,
                'is_featured'    => true,
                'discount'       => 20,
                'specifications' => json_encode([
                    'type'            => 'In-ear',
                    'connectivity'    => 'Bluetooth 5.3',
                    'battery'         => '6 hours',
                    'water_resistant' => 'IPX4',
                ]),
                'features' => json_encode([
                    'Active Noise Cancellation',
                    'Spatial Audio',
                    'MagSafe Charging Case',
                    'Adaptive EQ',
                ]),
            ],
            [
                'name'           => 'Bose QuietComfort Ultra',
                'description'    => 'Premium over-ear headphones with Bose Immersive Audio, world-class noise cancellation, and 24-hour battery.',
                'price'          => 379.99,
                'original_price' => 429.99,
                'image'          => 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&h=600&fit=crop',
                'rating'         => 4.8,
                'reviews'        => 3102,
                'category'       => 'Audio',
                'brand'          => 'Bose',
                'stock'          => 28,
                'is_new'         => true,
                'is_featured'    => true,
                'discount'       => 12,
                'specifications' => json_encode([
                    'type'             => 'Over-ear',
                    'connectivity'     => 'Bluetooth 5.3',
                    'battery'          => '24 hours',
                    'noise_cancelling' => 'CustomTune Technology',
                    'weight'           => '254g',
                ]),
                'features' => json_encode([
                    'Bose Immersive Audio',
                    'Aware Mode',
                    'Multipoint Pairing',
                    'USB-C Charging',
                    'Fold-flat Design',
                ]),
            ],

            // ─────────────────────────────────────────
            // WEARABLES
            // ─────────────────────────────────────────
            [
                'name'           => 'Apple Watch Ultra 2',
                'description'    => 'Titanium case, 49mm display, 100m water resistance, and advanced fitness tracking.',
                'price'          => 749.99,
                'original_price' => 799.99,
                'image'          => 'https://images.unsplash.com/photo-1434494878577-86c23bcb06b9?w=600&h=600&fit=crop',
                'rating'         => 4.7,
                'reviews'        => 2341,
                'category'       => 'Wearables',
                'brand'          => 'Apple',
                'stock'          => 12,
                'is_new'         => true,
                'is_featured'    => true,
                'discount'       => 6,
                'specifications' => json_encode([
                    'display'         => '49mm Retina',
                    'battery'         => '36 hours',
                    'water_resistant' => '100m',
                    'gps'             => 'Yes',
                ]),
                'features' => json_encode([
                    'Titanium Case',
                    'Dual-frequency GPS',
                    'Siren for emergency',
                    'Diving computer',
                ]),
            ],
            [
                'name'           => 'Samsung Galaxy Watch 6',
                'description'    => 'Sapphire crystal display, advanced sleep tracking, and heart rate monitoring.',
                'price'          => 299.99,
                'original_price' => 349.99,
                'image'          => 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&h=600&fit=crop',
                'rating'         => 4.6,
                'reviews'        => 1876,
                'category'       => 'Wearables',
                'brand'          => 'Samsung',
                'stock'          => 25,
                'is_new'         => false,
                'is_featured'    => false,
                'discount'       => 14,
                'specifications' => json_encode([
                    'display'         => '1.5-inch Super AMOLED',
                    'battery'         => '40 hours',
                    'water_resistant' => '50m',
                ]),
                'features' => json_encode([
                    'Body composition analysis',
                    'Sleep tracking',
                    'ECG monitor',
                    'Blood pressure monitor',
                ]),
            ],

            // ─────────────────────────────────────────
            // ACCESSORIES
            // ─────────────────────────────────────────
            [
                'name'           => 'Logitech MX Master 3S',
                'description'    => 'Ultra-fast scrolling, 8K DPI sensor, and quiet clicks for maximum productivity.',
                'price'          => 89.99,
                'original_price' => 99.99,
                'image'          => 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&h=600&fit=crop',
                'rating'         => 4.6,
                'reviews'        => 1876,
                'category'       => 'Accessories',
                'brand'          => 'Logitech',
                'stock'          => 56,
                'is_new'         => false,
                'is_featured'    => true,
                'discount'       => 10,
                'specifications' => json_encode([
                    'sensor'        => '8K DPI',
                    'buttons'       => '6',
                    'connectivity'  => 'Bluetooth + USB',
                    'battery'       => '70 days',
                ]),
                'features' => json_encode([
                    'MagSpeed Wheel',
                    'Quiet Clicks',
                    'Multi-device pairing',
                    'USB-C charging',
                ]),
            ],
            [
                'name'           => 'Keychron K2 Pro',
                'description'    => 'Wireless mechanical keyboard with hot-swappable switches and RGB backlight.',
                'price'          => 79.99,
                'original_price' => 99.99,
                'image'          => 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&h=600&fit=crop',
                'rating'         => 4.8,
                'reviews'        => 3421,
                'category'       => 'Accessories',
                'brand'          => 'Keychron',
                'stock'          => 34,
                'is_new'         => true,
                'is_featured'    => false,
                'discount'       => 20,
                'specifications' => json_encode([
                    'layout'       => '75%',
                    'switch_type'  => 'Gateron Pro',
                    'connectivity' => 'Bluetooth + USB-C',
                    'battery'      => '4000mAh',
                ]),
                'features' => json_encode([
                    'Hot-swappable',
                    'RGB Backlight',
                    'Mac/Windows layout',
                    'Wireless',
                ]),
            ],

            // ─────────────────────────────────────────
            // MONITORS
            // ─────────────────────────────────────────
            [
                'name'           => 'LG UltraGear 27GP950-B 4K',
                'description'    => '27-inch Nano IPS 4K gaming monitor with 144Hz, 1ms response time, and HDMI 2.1.',
                'price'          => 699.99,
                'original_price' => 799.99,
                'image'          => 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=600&h=600&fit=crop',
                'rating'         => 4.7,
                'reviews'        => 2187,
                'category'       => 'Monitors',
                'brand'          => 'LG',
                'stock'          => 17,
                'is_new'         => false,
                'is_featured'    => true,
                'discount'       => 13,
                'specifications' => json_encode([
                    'panel'          => 'Nano IPS',
                    'resolution'     => '3840 × 2160 (4K)',
                    'refresh_rate'   => '144Hz',
                    'response_time'  => '1ms GtG',
                    'hdr'            => 'VESA DisplayHDR 600',
                    'connectivity'   => 'HDMI 2.1, DisplayPort 1.4, USB-C',
                ]),
                'features' => json_encode([
                    'NVIDIA G-SYNC Compatible',
                    'AMD FreeSync Premium Pro',
                    'Height & Tilt Adjustable',
                    'RGB Sphere Lighting',
                    '3-Side Virtually Borderless',
                ]),
            ],
            [
                'name'           => 'Dell UltraSharp U2723D 27"',
                'description'    => 'IPS Black panel with 2000:1 contrast ratio, USB-C 90W charging, and factory-calibrated color accuracy.',
                'price'          => 529.99,
                'original_price' => 599.99,
                'image'          => 'https://images.unsplash.com/photo-1547119957-637f8679db1e?w=600&h=600&fit=crop',
                'rating'         => 4.8,
                'reviews'        => 1564,
                'category'       => 'Monitors',
                'brand'          => 'Dell',
                'stock'          => 20,
                'is_new'         => false,
                'is_featured'    => false,
                'discount'       => 12,
                'specifications' => json_encode([
                    'panel'         => 'IPS Black',
                    'resolution'    => '2560 × 1440 (QHD)',
                    'refresh_rate'  => '60Hz',
                    'contrast'      => '2000:1',
                    'connectivity'  => 'USB-C 90W, HDMI, DisplayPort, USB-A Hub',
                ]),
                'features' => json_encode([
                    'Factory Color Calibrated',
                    'USB-C 90W Power Delivery',
                    'Built-in KVM Switch',
                    'ComfortView Plus (Low Blue Light)',
                    'VESA Mount Compatible',
                ]),
            ],

            // ─────────────────────────────────────────
            // GAMING
            // ─────────────────────────────────────────
            [
                'name'           => 'PlayStation 5 Console',
                'description'    => 'Sony PS5 with ultra-high-speed SSD, ray tracing, 4K gaming, and the DualSense wireless controller.',
                'price'          => 499.99,
                'original_price' => 499.99,
                'image'          => 'https://images.unsplash.com/photo-1607853202273-797f1c22a38e?w=600&h=600&fit=crop',
                'rating'         => 4.9,
                'reviews'        => 14532,
                'category'       => 'Gaming',
                'brand'          => 'Sony',
                'stock'          => 6,
                'is_new'         => false,
                'is_featured'    => true,
                'discount'       => 0,
                'specifications' => json_encode([
                    'cpu'      => 'AMD Zen 2 (8-core 3.5GHz)',
                    'gpu'      => '10.3 TFLOPS, RDNA 2',
                    'ram'      => '16GB GDDR6',
                    'storage'  => '825GB NVMe SSD',
                    'optical'  => '4K UHD Blu-ray',
                    'output'   => '4K 120Hz / 8K',
                ]),
                'features' => json_encode([
                    'Ray Tracing',
                    'DualSense Haptic Feedback',
                    'Tempest 3D Audio',
                    'Backward Compatible with PS4',
                    'PlayStation Plus Required for Online',
                ]),
            ],
            [
                'name'           => 'Xbox Series X',
                'description'    => "Microsoft's most powerful console — 12 TFLOPS, Quick Resume, and Xbox Game Pass ready.",
                'price'          => 499.99,
                'original_price' => 499.99,
                'image'          => 'https://images.unsplash.com/photo-1621259182978-fbf93132d53d?w=600&h=600&fit=crop',
                'rating'         => 4.8,
                'reviews'        => 12341,
                'category'       => 'Gaming',
                'brand'          => 'Microsoft',
                'stock'          => 9,
                'is_new'         => false,
                'is_featured'    => true,
                'discount'       => 0,
                'specifications' => json_encode([
                    'cpu'     => 'AMD Zen 2 (8-core 3.8GHz)',
                    'gpu'     => '12 TFLOPS, RDNA 2',
                    'ram'     => '16GB GDDR6',
                    'storage' => '1TB NVMe SSD',
                    'optical' => '4K UHD Blu-ray',
                    'output'  => '4K 120Hz / 8K',
                ]),
                'features' => json_encode([
                    'Quick Resume (Multiple Games)',
                    'Xbox Game Pass Compatible',
                    'Auto HDR',
                    'DirectX Ray Tracing',
                    'Smart Delivery',
                ]),
            ],

            // ─────────────────────────────────────────
            // CAMERAS
            // ─────────────────────────────────────────
            [
                'name'           => 'Sony Alpha A7 IV',
                'description'    => '33MP full-frame BSI CMOS sensor, 4K 60fps video, 10fps burst, and real-time tracking AF.',
                'price'          => 2498.00,
                'original_price' => 2799.99,
                'image'          => 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600&h=600&fit=crop',
                'rating'         => 4.9,
                'reviews'        => 3876,
                'category'       => 'Cameras',
                'brand'          => 'Sony',
                'stock'          => 7,
                'is_new'         => false,
                'is_featured'    => true,
                'discount'       => 11,
                'specifications' => json_encode([
                    'sensor'       => '33MP Full-Frame BSI CMOS',
                    'iso'          => '100–51200 (expandable)',
                    'autofocus'    => '759-point Phase Detection',
                    'video'        => '4K 60fps / 1080p 120fps',
                    'burst'        => '10fps',
                    'stabilization'=> '5-axis IBIS (5.5 stops)',
                ]),
                'features' => json_encode([
                    'Real-time Eye AF (Human & Animal)',
                    'Dual CFexpress / SD Card Slots',
                    'Weather Sealed',
                    'Bluetooth / Wi-Fi / USB-C',
                    'Vari-Angle Touchscreen LCD',
                ]),
            ],
            [
                'name'           => 'GoPro HERO12 Black',
                'description'    => '5.3K60 video, HyperSmooth 6.0 stabilization, and unlimited recording without overheating.',
                'price'          => 349.99,
                'original_price' => 399.99,
                'image'          => 'https://images.unsplash.com/photo-1551703599-c4e3e84e7e6a?w=600&h=600&fit=crop',
                'rating'         => 4.7,
                'reviews'        => 6754,
                'category'       => 'Cameras',
                'brand'          => 'GoPro',
                'stock'          => 38,
                'is_new'         => true,
                'is_featured'    => false,
                'discount'       => 13,
                'specifications' => json_encode([
                    'video'           => '5.3K60 / 4K120 / 2.7K240',
                    'photo'           => '27MP',
                    'stabilization'   => 'HyperSmooth 6.0',
                    'water_resistant' => '10m without housing',
                    'battery'         => '1720 mAh (Enduro)',
                ]),
                'features' => json_encode([
                    'Unlimited Overheating-Free Recording',
                    'HDR Video',
                    'TimeWarp 3.0',
                    'Live Streaming 1080p',
                    'Removable Lens Mod Support',
                ]),
            ],
              [
        'name'           => 'MacBook Air 15" M3',
        'description'    => 'Thin, light, and incredibly capable. The 15-inch MacBook Air with M3 chip delivers up to 18 hours of battery life and a stunning Liquid Retina display.',
        'price'          => 1299.99,
        'original_price' => 1499.99,
        'image'          => 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&h=600&fit=crop',
        'rating'         => 4.8,
        'reviews'        => 4120,
        'category'       => 'Laptops',
        'brand'          => 'Apple',
        'stock'          => 18,
        'is_new'         => true,
        'is_featured'    => true,
        'discount'       => 13,
        'specifications' => json_encode([
            'processor' => 'Apple M3 (8-core)',
            'ram'       => '8GB Unified',
            'storage'   => '256GB SSD',
            'display'   => '15.3-inch Liquid Retina',
            'battery'   => 'Up to 18 hours',
            'weight'    => '3.3 lbs',
        ]),
        'features' => json_encode([
            'Fanless Design',
            '1080p FaceTime HD Camera',
            'MagSafe 3 Charging',
            'Wi-Fi 6E',
            'Two Thunderbolt 3 Ports',
        ]),
    ],
    [
        'name'           => 'HP Spectre x360 14',
        'description'    => 'Convertible 2-in-1 laptop with an OLED touch display, Intel Core Ultra 7, and premium aluminum chassis.',
        'price'          => 1449.99,
        'original_price' => 1649.99,
        'image'          => 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600&h=600&fit=crop',
        'rating'         => 4.6,
        'reviews'        => 1765,
        'category'       => 'Laptops',
        'brand'          => 'HP',
        'stock'          => 13,
        'is_new'         => true,
        'is_featured'    => false,
        'discount'       => 12,
        'specifications' => json_encode([
            'processor' => 'Intel Core Ultra 7 155H',
            'ram'       => '16GB LPDDR5',
            'storage'   => '1TB SSD',
            'display'   => '14-inch 2.8K OLED Touch',
            'battery'   => 'Up to 17 hours',
            'weight'    => '3.01 lbs',
        ]),
        'features' => json_encode([
            '360° Hinge',
            'HP Rechargeable MPP2.0 Tilt Pen',
            'Fingerprint Reader',
            'IR Camera',
            'Thunderbolt 4 x2',
        ]),
    ],
    [
        'name'           => 'ASUS ROG Zephyrus G14',
        'description'    => 'Ultra-slim gaming powerhouse with AMD Ryzen 9, NVIDIA RTX 4060, and a stunning 165Hz display.',
        'price'          => 1549.99,
        'original_price' => 1749.99,
        'image'          => 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=600&h=600&fit=crop',
        'rating'         => 4.7,
        'reviews'        => 2134,
        'category'       => 'Laptops',
        'brand'          => 'ASUS',
        'stock'          => 20,
        'is_new'         => true,
        'is_featured'    => true,
        'discount'       => 11,
        'specifications' => json_encode([
            'processor' => 'AMD Ryzen 9 7940HS',
            'gpu'       => 'NVIDIA GeForce RTX 4060',
            'ram'       => '16GB DDR5',
            'storage'   => '1TB NVMe SSD',
            'display'   => '14-inch 2.5K 165Hz',
            'battery'   => 'Up to 10 hours',
        ]),
        'features' => json_encode([
            'ROG Nebula Display',
            'MUX Switch',
            'AniMe Matrix LED Cover',
            'Dolby Atmos Audio',
            'Wi-Fi 6E',
        ]),
    ],
    [
        'name'           => 'Lenovo ThinkPad X1 Carbon Gen 11',
        'description'    => 'Legendary business laptop — featherlight at 2.48 lbs, Intel vPro, and enterprise-grade security.',
        'price'          => 1649.99,
        'original_price' => 1899.99,
        'image'          => 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=600&h=600&fit=crop',
        'rating'         => 4.8,
        'reviews'        => 1543,
        'category'       => 'Laptops',
        'brand'          => 'Lenovo',
        'stock'          => 10,
        'is_new'         => false,
        'is_featured'    => false,
        'discount'       => 13,
        'specifications' => json_encode([
            'processor' => 'Intel Core i7-1365U vPro',
            'ram'       => '16GB LPDDR5',
            'storage'   => '512GB SSD',
            'display'   => '14-inch 2.8K OLED',
            'battery'   => 'Up to 15 hours',
            'weight'    => '2.48 lbs',
        ]),
        'features' => json_encode([
            'MIL-SPEC Durability',
            'Fingerprint + IR Camera',
            'ThinkShield Security',
            'Rapid Charge (80% in 1hr)',
            'Thunderbolt 4',
        ]),
    ],
    [
        'name'           => 'Microsoft Surface Laptop 5',
        'description'    => 'Sleek laptop with a vibrant PixelSense touchscreen, Intel Evo platform, and all-day battery life.',
        'price'          => 1299.99,
        'original_price' => 1399.99,
        'image'          => 'https://images.unsplash.com/photo-1484788984921-03950022c9ef?w=600&h=600&fit=crop',
        'rating'         => 4.5,
        'reviews'        => 987,
        'category'       => 'Laptops',
        'brand'          => 'Microsoft',
        'stock'          => 15,
        'is_new'         => false,
        'is_featured'    => false,
        'discount'       => 7,
        'specifications' => json_encode([
            'processor' => 'Intel Core i7-1265U',
            'ram'       => '16GB LPDDR5x',
            'storage'   => '512GB SSD',
            'display'   => '13.5-inch PixelSense Touch',
            'battery'   => 'Up to 18 hours',
            'weight'    => '2.8 lbs',
        ]),
        'features' => json_encode([
            'PixelSense Touchscreen',
            'Alcantara Keyboard',
            'Wi-Fi 6',
            'USB-C + USB-A + Surface Connect',
            'Dolby Atmos Speakers',
        ]),
    ],
    [
        'name'           => 'Acer Swift X 16',
        'description'    => 'Creator laptop with a stunning 3.2K OLED display, AMD Ryzen 7, and NVIDIA RTX 4050 GPU.',
        'price'          => 1099.99,
        'original_price' => 1299.99,
        'image'          => 'https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=600&h=600&fit=crop',
        'rating'         => 4.5,
        'reviews'        => 812,
        'category'       => 'Laptops',
        'brand'          => 'Acer',
        'stock'          => 22,
        'is_new'         => false,
        'is_featured'    => false,
        'discount'       => 15,
        'specifications' => json_encode([
            'processor' => 'AMD Ryzen 7 7840U',
            'gpu'       => 'NVIDIA GeForce RTX 4050',
            'ram'       => '16GB LPDDR5',
            'storage'   => '1TB NVMe SSD',
            'display'   => '16-inch 3.2K OLED 60Hz',
            'battery'   => 'Up to 12 hours',
        ]),
        'features' => json_encode([
            '3.2K OLED Display',
            'DCI-P3 100% Color Gamut',
            'Thunderbolt 4',
            'Wi-Fi 6E',
            'Backlit Keyboard',
        ]),
    ],
 
    // ─────────────────────────────────────────
    // 🎧 HEADPHONES
    // ─────────────────────────────────────────
    [
        'name'           => 'Bose QuietComfort Ultra',
        'description'    => 'Premium over-ear headphones with Bose Immersive Audio, world-class noise cancellation, and 24-hour battery.',
        'price'          => 379.99,
        'original_price' => 429.99,
        'image'          => 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&h=600&fit=crop',
        'rating'         => 4.8,
        'reviews'        => 3102,
        'category'       => 'Headphones',
        'brand'          => 'Bose',
        'stock'          => 28,
        'is_new'         => true,
        'is_featured'    => true,
        'discount'       => 12,
        'specifications' => json_encode([
            'type'             => 'Over-ear',
            'connectivity'     => 'Bluetooth 5.3',
            'battery'          => '24 hours',
            'noise_cancelling' => 'CustomTune Technology',
            'weight'           => '254g',
        ]),
        'features' => json_encode([
            'Bose Immersive Audio',
            'Aware Mode',
            'Multipoint Pairing',
            'USB-C Charging',
            'Fold-flat Design',
        ]),
    ],
    [
        'name'           => 'Sennheiser Momentum 4 Wireless',
        'description'    => 'Audiophile-grade sound with 60-hour battery, adaptive ANC, and foldable premium design.',
        'price'          => 279.99,
        'original_price' => 349.99,
        'image'          => 'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=600&h=600&fit=crop',
        'rating'         => 4.7,
        'reviews'        => 2341,
        'category'       => 'Headphones',
        'brand'          => 'Sennheiser',
        'stock'          => 31,
        'is_new'         => false,
        'is_featured'    => true,
        'discount'       => 20,
        'specifications' => json_encode([
            'type'             => 'Over-ear',
            'connectivity'     => 'Bluetooth 5.2',
            'battery'          => '60 hours',
            'noise_cancelling' => 'Adaptive ANC',
            'weight'           => '293g',
        ]),
        'features' => json_encode([
            '60-Hour Battery Life',
            'Adaptive ANC',
            'Sound Personalization via App',
            'Foldable Design',
            'USB-C Fast Charging',
        ]),
    ],
    [
        'name'           => 'Jabra Evolve2 85',
        'description'    => 'Professional wireless headset with 10-mic ANC technology, 37-hour battery, and UC-certified audio.',
        'price'          => 449.99,
        'original_price' => 499.99,
        'image'          => 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=600&h=600&fit=crop',
        'rating'         => 4.6,
        'reviews'        => 1089,
        'category'       => 'Headphones',
        'brand'          => 'Jabra',
        'stock'          => 16,
        'is_new'         => false,
        'is_featured'    => false,
        'discount'       => 10,
        'specifications' => json_encode([
            'type'             => 'Over-ear',
            'connectivity'     => 'Bluetooth 5.0 + USB Dongle',
            'battery'          => '37 hours',
            'noise_cancelling' => '10-mic ANC',
            'weight'           => '340g',
        ]),
        'features' => json_encode([
            'UC & MS Teams Certified',
            'Busy Light Indicator',
            'Flip-to-Mute Boom Arm',
            'Wireless Charging Stand',
            'Multipoint Connection x3',
        ]),
    ],
    [
        'name'           => 'Audio-Technica ATH-M50xBT2',
        'description'    => 'Studio-quality wireless headphones based on the legendary M50x, with 50-hour battery and multipoint connection.',
        'price'          => 179.99,
        'original_price' => 199.99,
        'image'          => 'https://images.unsplash.com/photo-1520170350707-b2da59970118?w=600&h=600&fit=crop',
        'rating'         => 4.7,
        'reviews'        => 4567,
        'category'       => 'Headphones',
        'brand'          => 'Audio-Technica',
        'stock'          => 40,
        'is_new'         => false,
        'is_featured'    => false,
        'discount'       => 10,
        'specifications' => json_encode([
            'type'         => 'Over-ear',
            'connectivity' => 'Bluetooth 5.0',
            'battery'      => '50 hours',
            'driver'       => '45mm',
            'weight'       => '307g',
        ]),
        'features' => json_encode([
            'Studio-grade Sound',
            'Low Latency Mode',
            'Multipoint Connection',
            'Touch Controls',
            'USB-C Charging',
        ]),
    ],
    [
        'name'           => 'Anker Soundcore Space Q45',
        'description'    => 'Budget-friendly ANC headphones with 50-hour battery, Hi-Res Audio certification, and LDAC support.',
        'price'          => 79.99,
        'original_price' => 99.99,
        'image'          => 'https://images.unsplash.com/photo-1613040809024-b4ef7ba99bc3?w=600&h=600&fit=crop',
        'rating'         => 4.5,
        'reviews'        => 8934,
        'category'       => 'Headphones',
        'brand'          => 'Anker',
        'stock'          => 65,
        'is_new'         => false,
        'is_featured'    => false,
        'discount'       => 20,
        'specifications' => json_encode([
            'type'             => 'Over-ear',
            'connectivity'     => 'Bluetooth 5.3',
            'battery'          => '50 hours',
            'noise_cancelling' => 'Adaptive ANC',
            'weight'           => '253g',
        ]),
        'features' => json_encode([
            'Hi-Res Audio + LDAC',
            'Adaptive ANC 3.0',
            'Multi-mode Transparency',
            'Soundcore App EQ',
            'USB-C Fast Charging',
        ]),
    ],
    [
        'name'           => 'Beats Studio Pro',
        'description'    => 'Personalized Spatial Audio, USB-C lossless audio, and up to 40 hours of battery with ANC off.',
        'price'          => 299.99,
        'original_price' => 349.99,
        'image'          => 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=600&h=600&fit=crop',
        'rating'         => 4.5,
        'reviews'        => 2103,
        'category'       => 'Headphones',
        'brand'          => 'Beats',
        'stock'          => 23,
        'is_new'         => true,
        'is_featured'    => false,
        'discount'       => 14,
        'specifications' => json_encode([
            'type'             => 'Over-ear',
            'connectivity'     => 'Bluetooth 5.3',
            'battery'          => '40 hours (ANC off)',
            'noise_cancelling' => 'Active ANC',
            'weight'           => '260g',
        ]),
        'features' => json_encode([
            'Personalized Spatial Audio',
            'USB-C Lossless Audio',
            'Works with Android & Apple',
            'Transparency Mode',
            'On-ear Detection',
        ]),
    ],
 
    // ─────────────────────────────────────────
    // ⌚ SMARTWATCHES
    // ─────────────────────────────────────────
    [
        'name'           => 'Apple Watch Series 9 (45mm)',
        'description'    => 'The most capable Apple Watch ever with the new S9 chip, Double Tap gesture, and always-on Retina display.',
        'price'          => 429.99,
        'original_price' => 499.99,
        'image'          => 'https://images.unsplash.com/photo-1434494878577-86c23bcb06b9?w=600&h=600&fit=crop',
        'rating'         => 4.8,
        'reviews'        => 7654,
        'category'       => 'Smartwatches',
        'brand'          => 'Apple',
        'stock'          => 30,
        'is_new'         => true,
        'is_featured'    => true,
        'discount'       => 14,
        'specifications' => json_encode([
            'display'         => '45mm Always-On Retina',
            'chip'            => 'Apple S9',
            'battery'         => 'Up to 18 hours',
            'water_resistant' => '50m (WR50)',
            'connectivity'    => 'GPS + Cellular',
        ]),
        'features' => json_encode([
            'Double Tap Gesture',
            'Precision Finding for iPhone',
            'Blood Oxygen Sensor',
            'ECG App',
            'Crash Detection',
        ]),
    ],
    [
        'name'           => 'Garmin Fenix 7X Solar',
        'description'    => 'Premium multisport GPS watch with solar charging, 28-day battery, and full topographic maps.',
        'price'          => 799.99,
        'original_price' => 899.99,
        'image'          => 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&h=600&fit=crop',
        'rating'         => 4.8,
        'reviews'        => 3421,
        'category'       => 'Smartwatches',
        'brand'          => 'Garmin',
        'stock'          => 11,
        'is_new'         => false,
        'is_featured'    => true,
        'discount'       => 11,
        'specifications' => json_encode([
            'display'         => '1.4-inch MIP Touchscreen',
            'battery'         => '28 days (smartwatch), 122 days (solar expedition)',
            'water_resistant' => '100m',
            'gps'             => 'Multi-band GPS',
            'weight'          => '89g',
        ]),
        'features' => json_encode([
            'Solar Charging',
            'Full Topographic Maps',
            'Multi-sport Tracking (90+ sports)',
            'Pulse Ox Sensor',
            'Music Storage (2000 songs)',
        ]),
    ],
    [
        'name'           => 'Fitbit Sense 2',
        'description'    => 'Advanced health smartwatch with continuous EDA scan, ECG, skin temperature, and built-in GPS.',
        'price'          => 199.99,
        'original_price' => 249.99,
        'image'          => 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600&h=600&fit=crop',
        'rating'         => 4.4,
        'reviews'        => 4312,
        'category'       => 'Smartwatches',
        'brand'          => 'Fitbit',
        'stock'          => 35,
        'is_new'         => false,
        'is_featured'    => false,
        'discount'       => 20,
        'specifications' => json_encode([
            'display'         => '1.58-inch AMOLED',
            'battery'         => 'Up to 6 days',
            'water_resistant' => '50m',
            'gps'             => 'Built-in GPS',
            'weight'          => '40.5g',
        ]),
        'features' => json_encode([
            'Stress Management Score',
            'ECG & EDA Sensor',
            'Skin Temperature Tracking',
            '6 Months Fitbit Premium',
            'Sleep Profiling',
        ]),
    ],
    [
        'name'           => 'Google Pixel Watch 2',
        'description'    => 'Fitbit health tools, Wear OS by Google, continuous heart rate tracking, and 24-hour battery.',
        'price'          => 299.99,
        'original_price' => 349.99,
        'image'          => 'https://images.unsplash.com/photo-1617043786394-f977fa12eddf?w=600&h=600&fit=crop',
        'rating'         => 4.5,
        'reviews'        => 2198,
        'category'       => 'Smartwatches',
        'brand'          => 'Google',
        'stock'          => 20,
        'is_new'         => true,
        'is_featured'    => false,
        'discount'       => 14,
        'specifications' => json_encode([
            'display'         => '1.2-inch AMOLED Always-On',
            'chip'            => 'Qualcomm W5+ Gen 1',
            'battery'         => 'Up to 24 hours',
            'water_resistant' => '50m',
            'os'              => 'Wear OS 4',
        ]),
        'features' => json_encode([
            'Fitbit Safety Check',
            'Continuous Electrodermal Activity',
            'Irregular Heart Rhythm Notification',
            'Google Assistant & Maps',
            'Emergency SOS',
        ]),
    ],
    [
        'name'           => 'Amazfit GTR 4',
        'description'    => 'Feature-packed smartwatch with dual-band GPS, 150+ sport modes, and an impressive 14-day battery.',
        'price'          => 139.99,
        'original_price' => 179.99,
        'image'          => 'https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=600&h=600&fit=crop',
        'rating'         => 4.4,
        'reviews'        => 5671,
        'category'       => 'Smartwatches',
        'brand'          => 'Amazfit',
        'stock'          => 45,
        'is_new'         => false,
        'is_featured'    => false,
        'discount'       => 22,
        'specifications' => json_encode([
            'display'         => '1.43-inch AMOLED',
            'battery'         => 'Up to 14 days',
            'water_resistant' => '50m (5ATM)',
            'gps'             => 'Dual-band GPS',
            'weight'          => '34g',
        ]),
        'features' => json_encode([
            '150+ Sport Modes',
            'Zepp OS 2.0',
            'Alexa Built-in',
            'Bluetooth Phone Calls',
            'Blood Oxygen & Stress Monitor',
        ]),
    ],
 
    // ─────────────────────────────────────────
    // 🖱️ MOUSE
    // ─────────────────────────────────────────
    [
        'name'           => 'Razer DeathAdder V3 Pro',
        'description'    => 'Iconic ergonomic gaming mouse with 30K DPI optical sensor, 90-hour battery, and ultra-lightweight 64g chassis.',
        'price'          => 149.99,
        'original_price' => 159.99,
        'image'          => 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&h=600&fit=crop',
        'rating'         => 4.8,
        'reviews'        => 3456,
        'category'       => 'Mouse',
        'brand'          => 'Razer',
        'stock'          => 38,
        'is_new'         => true,
        'is_featured'    => true,
        'discount'       => 6,
        'specifications' => json_encode([
            'sensor'       => 'Razer Focus Pro 30K DPI',
            'buttons'      => '7 Programmable',
            'connectivity' => 'Razer HyperSpeed Wireless',
            'battery'      => '90 hours',
            'weight'       => '64g',
        ]),
        'features' => json_encode([
            'Razer HyperSpeed Wireless',
            'Focus Pro 30K Optical Sensor',
            'Intelligent Tracking',
            'Asymmetric Cut Design',
            'Razer Synapse 3 Compatible',
        ]),
    ],
    [
        'name'           => 'Logitech G Pro X Superlight 2',
        'description'    => 'Pro-grade ultra-lightweight gaming mouse at just 60g with HERO 2 25K sensor and LIGHTSPEED wireless.',
        'price'          => 159.99,
        'original_price' => 179.99,
        'image'          => 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=600&h=600&fit=crop',
        'rating'         => 4.9,
        'reviews'        => 5123,
        'category'       => 'Mouse',
        'brand'          => 'Logitech',
        'stock'          => 27,
        'is_new'         => true,
        'is_featured'    => true,
        'discount'       => 11,
        'specifications' => json_encode([
            'sensor'       => 'HERO 2 25,600 DPI',
            'buttons'      => '5',
            'connectivity' => 'LIGHTSPEED Wireless',
            'battery'      => '95 hours',
            'weight'       => '60g',
        ]),
        'features' => json_encode([
            'LIGHTSPEED Wireless',
            'Zero Additive PTFE Feet',
            'Symmetrical Design',
            'eSports-grade Performance',
            'USB-C Charging',
        ]),
    ],
    [
        'name'           => 'Apple Magic Mouse',
        'description'    => 'Sleek, rechargeable multi-touch mouse with a seamless surface for fluid scrolling and gestures.',
        'price'          => 79.99,
        'original_price' => 99.99,
        'image'          => 'https://images.unsplash.com/photo-1563191911-e65f8655ebf9?w=600&h=600&fit=crop',
        'rating'         => 4.3,
        'reviews'        => 6780,
        'category'       => 'Mouse',
        'brand'          => 'Apple',
        'stock'          => 50,
        'is_new'         => false,
        'is_featured'    => false,
        'discount'       => 20,
        'specifications' => json_encode([
            'surface'      => 'Multi-touch',
            'connectivity' => 'Bluetooth',
            'battery'      => 'Lightning Rechargeable',
            'weight'       => '99g',
            'compatibility'=> 'macOS',
        ]),
        'features' => json_encode([
            'Multi-Touch Surface',
            'Swipe Between Pages',
            'Full-page Scroll',
            'Lightning Charging',
            'Laser Tracking Engine',
        ]),
    ],
    [
        'name'           => 'SteelSeries Aerox 5 Wireless',
        'description'    => 'Holey design gaming mouse with 9 buttons, 80-hour battery, and TrueMove Air precision optical sensor.',
        'price'          => 129.99,
        'original_price' => 149.99,
        'image'          => 'https://images.unsplash.com/photo-1586349906319-47f4a4a34f08?w=600&h=600&fit=crop',
        'rating'         => 4.6,
        'reviews'        => 1876,
        'category'       => 'Mouse',
        'brand'          => 'SteelSeries',
        'stock'          => 32,
        'is_new'         => false,
        'is_featured'    => false,
        'discount'       => 13,
        'specifications' => json_encode([
            'sensor'       => 'TrueMove Air 18,000 DPI',
            'buttons'      => '9 Programmable',
            'connectivity' => '2.4GHz Wireless + Bluetooth',
            'battery'      => '80 hours',
            'weight'       => '74g',
        ]),
        'features' => json_encode([
            'AquaBarrier Water Resistant',
            'Quantum 2.0 Wireless',
            'SteelSeries GG Software',
            'Holey Shell Design',
            'Dual Wireless Modes',
        ]),
    ],
    [
        'name'           => 'Corsair Dark Core RGB Pro SE',
        'description'    => 'High-performance wireless gaming mouse with Qi wireless charging, 18K DPI sensor, and 8 programmable buttons.',
        'price'          => 89.99,
        'original_price' => 109.99,
        'image'          => 'https://images.unsplash.com/photo-1612287230202-1ff1d85d1bdf?w=600&h=600&fit=crop',
        'rating'         => 4.5,
        'reviews'        => 2341,
        'category'       => 'Mouse',
        'brand'          => 'Corsair',
        'stock'          => 29,
        'is_new'         => false,
        'is_featured'    => false,
        'discount'       => 18,
        'specifications' => json_encode([
            'sensor'       => '18,000 DPI Optical',
            'buttons'      => '8 Programmable',
            'connectivity' => 'SLIPSTREAM 2.4GHz + Bluetooth + USB',
            'battery'      => '50 hours',
            'weight'       => '133g',
        ]),
        'features' => json_encode([
            'Qi Wireless Charging',
            'Interchangeable Side Grips',
            'iCUE RGB Lighting',
            'SLIPSTREAM Wireless',
            'Three-way Connectivity',
        ]),
    ],
 
    // ─────────────────────────────────────────
    // ⌨️ KEYBOARDS
    // ─────────────────────────────────────────
    [
        'name'           => 'Logitech MX Keys S',
        'description'    => 'Smart illuminated wireless keyboard with perfect stroke keys, USB-C charging, and multi-OS compatibility.',
        'price'          => 109.99,
        'original_price' => 129.99,
        'image'          => 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&h=600&fit=crop',
        'rating'         => 4.7,
        'reviews'        => 4231,
        'category'       => 'Keyboards',
        'brand'          => 'Logitech',
        'stock'          => 40,
        'is_new'         => true,
        'is_featured'    => true,
        'discount'       => 15,
        'specifications' => json_encode([
            'layout'       => 'Full-size',
            'connectivity' => 'Bluetooth + Logi Bolt USB',
            'battery'      => '10 days (backlit), 5 months (unlit)',
            'backlight'    => 'Smart Adaptive Backlight',
            'compatibility'=> 'Windows, macOS, Linux, iOS, Android',
        ]),
        'features' => json_encode([
            'Smart Actions Customization',
            'Backlit Spherically Dished Keys',
            'Easy-Switch (3 Devices)',
            'USB-C Charging',
            'Flow Cross-computer Control',
        ]),
    ],
    [
        'name'           => 'Razer BlackWidow V4 Pro',
        'description'    => 'Full-size wireless mechanical gaming keyboard with Razer Green Clicky switches, multi-function dial, and Chroma RGB.',
        'price'          => 229.99,
        'original_price' => 279.99,
        'image'          => 'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=600&h=600&fit=crop',
        'rating'         => 4.7,
        'reviews'        => 2109,
        'category'       => 'Keyboards',
        'brand'          => 'Razer',
        'stock'          => 18,
        'is_new'         => true,
        'is_featured'    => true,
        'discount'       => 18,
        'specifications' => json_encode([
            'layout'       => 'Full-size',
            'switch'       => 'Razer Green (Clicky)',
            'connectivity' => 'Razer HyperSpeed Wireless + Bluetooth + USB-C',
            'battery'      => '200 hours',
            'backlight'    => 'Razer Chroma RGB (per-key)',
        ]),
        'features' => json_encode([
            'Multi-function Command Dial',
            '6 Dedicated Macro Keys',
            'Magnetic Wrist Rest Included',
            'Razer Synapse 3 Compatible',
            'Triple Connectivity Modes',
        ]),
    ],
    [
        'name'           => 'Corsair K100 RGB',
        'description'    => 'Flagship gaming keyboard with CORSAIR AXON 4,000Hz polling, OPX optical-mechanical switches, and iCUE Command Wheel.',
        'price'          => 199.99,
        'original_price' => 249.99,
        'image'          => 'https://images.unsplash.com/photo-1541140532154-b024d705b90a?w=600&h=600&fit=crop',
        'rating'         => 4.8,
        'reviews'        => 3871,
        'category'       => 'Keyboards',
        'brand'          => 'Corsair',
        'stock'          => 14,
        'is_new'         => false,
        'is_featured'    => true,
        'discount'       => 20,
        'specifications' => json_encode([
            'layout'       => 'Full-size',
            'switch'       => 'CORSAIR OPX Optical-Mechanical',
            'polling_rate' => '4,000Hz (AXON)',
            'connectivity' => 'USB',
            'backlight'    => 'Per-key RGB (44-zone)',
        ]),
        'features' => json_encode([
            '4,000Hz AXON Polling Rate',
            'iCUE Command Wheel',
            '50M Keystroke Durability',
            '6 Dedicated Macro Keys',
            'Aircraft-grade Aluminum Frame',
        ]),
    ],
    [
        'name'           => 'Ducky One 3 TKL',
        'description'    => 'Premium tenkeyless mechanical keyboard with hot-swap PCB, Quack Mechanics, and double-shot PBT keycaps.',
        'price'          => 109.99,
        'original_price' => 129.99,
        'image'          => 'https://images.unsplash.com/photo-1604754742629-3e5728249d73?w=600&h=600&fit=crop',
        'rating'         => 4.8,
        'reviews'        => 1432,
        'category'       => 'Keyboards',
        'brand'          => 'Ducky',
        'stock'          => 22,
        'is_new'         => false,
        'is_featured'    => false,
        'discount'       => 15,
        'specifications' => json_encode([
            'layout'       => 'Tenkeyless (TKL)',
            'switch'       => 'Cherry MX (choice of 6 types)',
            'keycaps'      => 'Double-shot PBT',
            'connectivity' => 'USB-C Detachable',
            'backlight'    => 'RGB',
        ]),
        'features' => json_encode([
            'Hot-swappable PCB',
            'Quack Mechanics Sound Dampening',
            'Double-shot PBT Keycaps',
            'NKRO Anti-Ghosting',
            'USB-C Detachable Cable',
        ]),
    ],
    [
        'name'           => 'SteelSeries Apex Pro TKL Wireless',
        'description'    => 'World\'s first adjustable actuation mechanical keyboard — set each key from 0.1mm to 4.0mm travel.',
        'price'          => 199.99,
        'original_price' => 239.99,
        'image'          => 'https://images.unsplash.com/photo-1561112078-7d24e04c3407?w=600&h=600&fit=crop',
        'rating'         => 4.7,
        'reviews'        => 2765,
        'category'       => 'Keyboards',
        'brand'          => 'SteelSeries',
        'stock'          => 16,
        'is_new'         => true,
        'is_featured'    => false,
        'discount'       => 17,
        'specifications' => json_encode([
            'layout'       => 'Tenkeyless (TKL)',
            'switch'       => 'SteelSeries OmniPoint 2.0',
            'actuation'    => '0.1mm – 4.0mm (per-key)',
            'connectivity' => 'Quantum 2.0 Wireless + USB-C',
            'battery'      => '40 hours',
        ]),
        'features' => json_encode([
            'Per-key Adjustable Actuation',
            'OLED Smart Display',
            'Quantum 2.0 Wireless',
            'Rapid Trigger Mode',
            'Prism RGB Per-key Lighting',
        ]),
            ],
 

        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}